// Copyright (c) 2019 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(l){var e,a={_breaker:{},_start:null,each:function(){var b,c=function(d,c){return d===a._breaker||Boolean(c)&&a.elapsed()>b};return function(d,f,g){var h,e;e=a.type(d);if(1===arguments.length)b=arguments[0];else if(g=a.extend({timeout:!1},g),"object"===e&&d.hasOwnProperty)for(h in d){if(d.hasOwnProperty(h)&&c(f(d[h],h),g.timeout))break}else if(d){h=0;for(e=d.length;h<e&&!c(f(d[h],h),g.timeout);h++);}}}(),extend:function(a){var c,d,f,g,h=arguments.length;a=a||{};for(d=1;d<h;d++)if(g=arguments[d],
void 0!==g&&null!==g)for(f in g)c=g[f],a!==c&&void 0!==c&&(a[f]=c);return a},noop:function(){},type:function(){var a=function(a,b){try{return("function"===typeof window[b]||"object"===typeof window[b])&&a instanceof window[b]}catch(f){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in
c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};a.extend(a,{addClass:function(b,c){a.hasClass(b,c)||(b.className=(b.className?b.className+" ":"")+c)},all:function(b,c){var d="array"===a.type(b)?[]:{};a.each(b,function(b,g){c(b,g)&&("array"===a.type(d)?d.push(b):d[g]=b)});return d},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},apiCallback:function(b,c){return function(d){"string"===a.type(d)&&(d={response:[d]});b.apply(c,d.response.concat(d.data))}},
attributes:function(b,c){var d;c=c||{};for(d in c)"function"===a.type(b.setAttribute)?b.setAttribute(d,c[d]):b["class"===d?"className":d]=c[d]},attrValues:function(a,c,d){return(c=a[c])&&c.split?c.split(d||" "):[]},batchable:function(b,c){c=c||a.noop;var d=function(){return a.extend({batch:!0,timeout:100},c())},f=a.traits.cors&&a.traits.json,g=[],h=null,e=function(){null!==h&&(clearTimeout(h),h=null);1===g.length?b.apply(null,g[0].arguments):1<g.length&&b.apply(null,g);g=[]},k=function(){g.push({arguments:a.toArray(arguments),
batch:!0});!f||!d().batch?e():null===h&&(h=setTimeout(a.entryPoint(a.bind(function(){e()},this)),d().timeout))};a.extend(k,{flush:e,now:b});return k},batchArgs:function(b,c){return a.map(b,function(a){return void 0===c?a.arguments:a.arguments[c]})},batchCallType:function(b){var c;return a.reduce(null,b,function(a,b){c=b[0];return null!==a&&c!==a?"batch":c})},batched:function(b){b=a.toArray(b);if("array"===a.type(b))return a.all(b,function(b){return"object"===a.type(b)&&b.batch&&"array"===a.type(b.arguments)}).length===
b.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var b={},c="vglnk_"+(new Date).getTime(),d=0;return function(f,g,h){if(!f||"string"===a.type(f))h=g,g=f,f=b;var e=f[c];if(e||void 0!==h)return e||(e=++d),b[e]||(f[c]=e,b[e]={}),void 0!==h&&(b[e][g]=h),"string"===typeof g?b[e][g]:b[e]}}(),canonicalizeHostname:function(){var b={};return function(c){"string"===typeof c&&(c=a.createA(c));try{return b[c.hostname]||(b[c.hostname]=c.hostname?c.hostname.toString().toLowerCase().replace(/^www\./,
"").replace(/:.*$/,""):""),b[c.hostname]}catch(d){return""}}}(),clone:function(b){return a.extend({},b)},commonParams:function(b,c){var d;c=c||{};d={drKey:c.key?null:c.dr_key,key:c.key,libId:c.library_id,subId:c.sub_id};("click"===b||"ping"===b)&&a.extend(d,{cuid:c.cuid,loc:window.document.location.href,v:1},d);return d},contains:function(b,c,d){return Boolean(a.find(b,function(a){return a===c},d))},context:function(b){"element"===a.type(b)&&(b=b.ownerDocument);"document"===a.type(b)&&(b=b.defaultView||
b.parentWindow);if("window"===a.type(b))return b},contextIsAncestor:function(a,c){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,d===c)return!0;return!1},cors:function(b,c,d){var f;f=new window.XMLHttpRequest;f.onreadystatechange=function(){if(4===f.readyState&&200===f.status){var b=a.noop,c=[],g;if(d)d(f.responseText);else if("string"===a.type(f.responseText)&&(g=f.responseText.match(/^\s*(?:\/\*\*\/)?([^(\s]+)\s*\((.*)\);?\s*$/)))b=g[1].replace(/(^\s+|\s+$)/g,""),c=a.fromJSON("["+g[2]+"]"),
window[b].apply(window,c)}};try{return f.open("POST",b),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.withCredentials=!0,f.send(c),!0}catch(g){return!1}},createA:function(b,c){return a.createEl("a",{href:b,target:c})},createEl:function(b,c,d,f){b=(f||document).createElement(b);a.attributes(b,c);a.css(b,d);return b},css:function(b,c){var d,f,g,h;if("object"===a.type(c))for(d in c)try{b.style[d]=c[d]}catch(e){}else try{return f=window.getComputedStyle(b),g=a.toArray(arguments).slice(1),
h=a.reduce({},g,function(a,b){a[b]=f.getPropertyValue(b);return a}),1===g.length?h[g[0]]:h}catch(k){return}return b},destructing:function(a){return function(a){var b=!1,f;return function(){b||(f=a.apply(null,arguments),b=!0);return f}}(a)},elapsed:function(a){return(a=a||this._start)?(new Date).getTime()-a.getTime():0},entryPoint:function(b){return a.exceptionLogger(function(){var c;a._start=new Date;a.observer.pause();c=b.apply(this,arguments);a.observer.resume();return c})},escapeRegExp:function(){var a;
return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,d=a.target||a.srcElement;do{try{c=d.nodeType}catch(f){break}if(1===c&&(a=d.tagName.toUpperCase(),"A"===a||"AREA"===a))return d;d=d.parentNode}while(d)},every:function(b,c){return Boolean(!a.some(b,function(a){return!c(a)}))},exceptionLogger:function(){var b=!1,c=a.noop;return function(a,f){if(void 0!==f)b=f,c=a;else return function(){if(b)try{return a.apply(this,arguments)}catch(f){c(f)}else return a.apply(this,
arguments)}}}(),find:function(b,c,d){var f;a.each(b,function(b,d){if(c(b,d))return f=b,a._breaker},d);return f},generateNodeFilter:function(){var b=function(a,b){var g,e;b=","+b.join(",")+",";g=0;for(e=a.length;g<e;g++)if(c(a[g],b))return!0;return!1},c=function(a,b){return-1!==b.indexOf(","+a+",")};return function(d){d=a.extend({custom:null,classes:[],rels:[],selectors:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");a.isArray(d.selectors)&&(d.selectors=d.selectors.join(","));
d.selectors&&d.selectors.length&&a.select(d.selectors);return function(f,g){g=a.extend({ancestors:!0,self:!0},g);var e=function(f,g){var e;if(e=!(d.tags&&d.tags.length&&c(f.nodeName.toLowerCase(),d.tags))){if(e=d.classes)if(e=d.classes.length){e=d.classes;var h=a.attrValues(f,"className");e=b(e,h)}if(e=!e){if(e=d.rels)if(e=d.rels.length)e=d.rels,h=a.attrValues(f,"rel"),e=c(f.nodeName.toLowerCase(),",a,")&&b(e,h);e=!e&&!("function"===a.type(d.custom)&&d.custom(f,g))}}return e};if(g.self&&!e(f,!0))return!1;
if(g.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!e(f,!1))return!1;return!0}}}(),fromJSON:function(b){if(a.traits.json)try{return window.JSON.parse(b)}catch(c){}},fromQuery:function(b){"?"===b.substr(0,1)&&(b=b.substr(1));b=b.split("&");var c={};a.each(b,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var b,c=arguments.length,d=Infinity,f=Infinity,g=-Infinity,e=-Infinity,m;for(b=0;b<c;b++)m=a.position(arguments[b]),
d=Math.min(d,m.x),f=Math.min(f,m.y),g=Math.max(g,m.x+arguments[b].offsetWidth),e=Math.max(e,m.y+arguments[b].offsetHeight);return{x:d,y:f,w:g-d,h:e-f,x1:d,y1:f,x2:g,y2:e}},getActualHref:function(b){return a.cache(b,"href")||b.href},hasAttrValue:function(b,c,d,f){return c?a.contains(a.attrValues(b,c,f),d):!1},hasClass:function(b,c){return a.hasAttrValue(b,"className",c)},hasRel:function(b,c){return a.hasAttrValue(b,"rel",c)},isArray:function(b){return"array"===a.type(b)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&
a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},isVisible:function(a){return Boolean(a.offsetHeight||a.offsetWidth||!a.getClientRects||a.getClientRects().length)},jsonp:function(b){var c=document.getElementsByTagName("script")[0];b=a.createEl("script",{type:"text/javascript",src:b});c.parentNode.insertBefore(b,c)},links:function(){var b=["http:","https:"],c=function(c,f){return a.all(c,function(c){return c.href&&(!f.filter_by_scheme||
a.contains(b,c.protocol))&&(!f.filter_homepages||"/"!==c.pathname)&&(!f.filter_internal||c.hostname!==a.context(c).location.hostname)})};return function(b,f,g){f=f||"";g=a.extend({filter_homepages:!0,filter_internal:!0,filter_by_scheme:!0},g);f=a.map(f.split(","),function(a){return a+" a[href]"}).join(",");return c(a.withScope(b,f,{ancestors:!1,consolidate:!0}),g)}}(),map:function(b,c,d){return a.reduce([],b,function(a,b,d){a.push(c(b,d));return a},d)},matches:function(b,c){if("element"!==a.type(b))return!1;
try{return this.Sizzle.matchesSelector(b,c)}catch(d){return!0}},mergeable:function(b){var c=function(){return a.extend({batchable:!0,batchFn:a.noop,nonBatchFn:a.noop,timeout:100},b())};return a.batchable(function(){a.batched(arguments)?c().batchable?a.each(a.batchArgs(arguments),function(a){c().batchFn.apply(this,a)}):c().nonBatchFn.apply(this,arguments):c().nonBatchFn.apply(this,arguments)},function(){return{batch:!0,timeout:c().timeout}})},mergeParams:function(b){var c,d,f,g=arguments.length,e=
function(d,f){c=b[f];b.hasOwnProperty(f)&&a.isArray(d)&&a.isArray(c)?b[f]=a.unique(c.concat(d)):b[f]=d};for(d=1;d<g;d++)f=arguments[d],a.each(f,e);return a.prune(b)},nodesOfType:function(b){var c=a.toArray(arguments).slice(1);return a.all(b,function(b){return a.contains(c,b.nodeType)})},on:function(){var b;return function(c,d,f){var g,e,m;if(1===arguments.length)b=c;else{if(2===arguments.length){if(!b)return;f=d;d=c;c=b}else g=a.toArray(arguments).slice(3,arguments.length);try{e=c["on"+d]}catch(k){}"function"===
typeof e&&(c["on"+d]=a.bind(function(b){b=b||window.event;var d=e.apply(c,arguments);this.exceptionLogger(function(){return b?(void 0!==d&&!1!==b.returnValue&&(b.returnValue=d),a.isDefaultPrevented(b)&&"function"===a.type(b.preventDefault)&&b.preventDefault(),b.returnValue):d})()},this));m=a.entryPoint(function(){if(b.enabled())return f.apply(null,a.toArray(arguments).concat(g||[]))});c.addEventListener?c.addEventListener(d,m,!1):c.attachEvent&&c.attachEvent("on"+d,m)}}}(),packageArgs:function(){return a.toArray(arguments)},
position:function(b,c){var d,f=0,e=0,h=0,m=0;c=c||document;if(!a.isInDom(b))return!1;d=b;do f+=d.offsetLeft,e+=d.offsetTop,d=d.offsetParent;while(d);d=b;do h+=d.scrollLeft,m+=d.scrollTop,d=d.parentNode;while(d&&d!==c.body);return{x:f-h,y:e-m}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(b){a.each(b,function(a,d){(null===a||void 0===a)&&delete b[d]});return b},ready:function(){var b=!1,c=[],d=!1,f,e,h,m,k;document.addEventListener?h=function(){document.removeEventListener("DOMContentLoaded",
h,!1);k()}:document.attachEvent&&(m=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),k())});f=function(){if(!b){b=!0;if("interactive"===document.readyState||"complete"===document.readyState)return k();if(document.addEventListener)document.addEventListener("DOMContentLoaded",h,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",m);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&e()}a.on(window,
"load",k)}};e=function(){if(!d){try{document.documentElement.doScroll("left")}catch(b){setTimeout(a.entryPoint(e),1);return}k()}};k=function(){if(!d){if(!document.body)return setTimeout(a.entryPoint(k),13);d=!0;c&&(a.each(c,function(a){a()}),c=null)}};return function(a){f();d?a():c.push(a)}}(),reduce:function(b,c,d,f){a.each(c,function(a,c){b=d(b,a,c)},f);return b},reformatKeys:function(b){var c,d,f=function(a){return"_"+a.toLowerCase()};for(c in b)d=c.replace(/([A-Z])/g,f),"object"===a.type(b[c])&&
(b[c]=a.reformatKeys(b[c])),d!==c&&(b[d]=b[c],delete b[c]);return b},removeClass:function(b,c){if(a.hasClass(b,c)){var d,f,e=a.attrValues(b,"className");d=0;for(f=e.length;d<f;d++)e[d]===c&&delete e[d];b.className=e.join(" ")}},request:function(b,c,d){var f,e,h,m=a.uniqid("vglnk_"),k=a.toArray(arguments).slice(3,arguments.length),n=function(b,c,d){var f={},e=!!c.length,g=!0===d||!1===d;if(e||g)b=a.createA(b),e&&(f.search="?"+c),g&&(c=b.protocol||a.context(b).location.protocol||"http:",f.protocol=
c.replace(/s?:$/,function(){return d?"s:":":"})),b=a.extend(b,f).href;return b};e=function(b,c){var d={},f=a.commonParams();d[c]={};a.each(b,function(a,b){b in f?d[b]=a:d[c][b]=a});d[c]=a.toJSON(d[c]);return a.prune(d)};d=a.extend({fn:a.noop,json_payload:null,jsonp:!0,"return":!1,ssl:null,timeout:null},d);"string"===typeof d.fn?(f=window[d.fn],m=d.fn):"function"===typeof d.fn&&(f=d.fn);"function"===a.type(f)&&(h=a.entryPoint(a.destructing(function(){var b,e;d.json_payload&&(e=d.json_payload,b=a.fromJSON(c[e]),
c=a.extend(c,b),delete c[e]);f({response:a.toArray(arguments),data:k,args:c});window[m]&&(window[m]=void 0)})),null!==d.timeout&&setTimeout(h,d.timeout));d.json_payload&&a.traits.cors&&(c=e(c,d.json_payload));!0===d.jsonp&&(window[m]=h,c=a.extend({format:"jsonp",jsonp:m},c));e=a.toQuery(c);return d["return"]?n(b,e,d.ssl):a.traits.json&&a.traits.cors&&a.cors(n(b,"",d.ssl),e,d.jsonp?null:h)?!0:a.jsonp(n(b,e,d.ssl))},rootContext:function(a){a=this.context(a);try{for(;a&&a.parent!==a;)a=a.parent}catch(c){}return a},
select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},some:function(b,c){return Boolean(a.find(b,function(a){return c(a)}))},stopPropagation:function(a){a&&a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},time:function(){return(new Date).getTime()},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var d,f,e=[];d=0;for(f=a.length;d<f;d++)e[d]=a[d];return e}},toJSON:function(b){if(a.traits.json)try{return window.JSON.stringify(b)}catch(c){}},
toQuery:function(b){var c="";a.each(a.prune(b),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(b,c){return a.extend(a.createA(b),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(b){return a.reduce([],b,function(b,d){a.contains(b,d)||b.push(d);return b})},unlink:function(a){var c,d=document.createDocumentFragment();if(a.parentNode){for(;null!==(c=a.firstChild);)d.appendChild(c);
a.parentNode.insertBefore(d,a);a.parentNode.removeChild(a)}},withScope:function(){var b=function(b,d,f){if(f.self&&a.contains(d,b,{timeout:!0}))return b;if(f.ancestors)return a.find(a.ancestors(b).slice(0),function(b){return a.contains(d,b,{timeout:!0})},{timeout:!0})};return function(c,d,f){var e,h=a.select(d);f=a.extend({ancestors:!0,consolidate:!1,descendants:!0,self:!0},f);f.descendants&&(e=a.map(h,function(b){return[b,a.ancestors(b)]},{timeout:!0}));c=a.all(a.map(c,function(c){var d,k=[];(d=
b(c,h,f))?k.push(d):1===c.nodeType&&f.descendants&&a.each(e,function(b){var d=b[0];a.contains(b[1],c,{timeout:!0})&&k.push(d)},{timeout:!0});return[c,k]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return f.consolidate?a.unique(a.reduce([],c,function(a,b){return a.concat(b[1])},{timeout:!0})):c}}()});var r=function(){var b=a.find(a.toArray(arguments),function(b){return"function"===a.type(b)});b&&(a.Sizzle=b())};r.amd=!0;(function(a){function c(a,b,c,d){var f,e,g,h,k;(b?b.ownerDocument||
b:E)!==B&&L(b);b=b||B;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(h=b.nodeType)&&9!==h)return[];if(G&&!d){if(f=oa.exec(a))if(g=f[1])if(9===h)if((e=b.getElementById(g))&&e.parentNode){if(e.id===g)return c.push(e),c}else return c;else{if(b.ownerDocument&&(e=b.ownerDocument.getElementById(g))&&V(b,e)&&e.id===g)return c.push(e),c}else{if(f[2])return M.apply(c,b.getElementsByTagName(a)),c;if((g=f[3])&&y.getElementsByClassName&&b.getElementsByClassName)return M.apply(c,b.getElementsByClassName(g)),
c}if(y.qsa&&(!C||!C.test(a))){e=f=z;g=b;k=9===h&&a;if(1===h&&"object"!==b.nodeName.toLowerCase()){h=W(a);(f=b.getAttribute("id"))?e=f.replace(pa,"\\$&"):b.setAttribute("id",e);e="[id='"+e+"'] ";for(g=h.length;g--;)h[g]=e+w(h[g]);g=da.test(a)&&I(b.parentNode)||b;k=h.join(",")}if(k)try{return M.apply(c,g.querySelectorAll(k)),c}catch(m){}finally{f||b.removeAttribute("id")}}}return ga(a.replace(Z,"$1"),b,c,d)}function d(){function a(c,d){b.push(c+" ")>u.cacheLength&&delete a[b.shift()];return a[c+" "]=
d}var b=[];return a}function f(a){a[z]=!0;return a}function e(a){var b=B.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function h(a,b){for(var c=a.split("|"),d=a.length;d--;)u.attrHandle[c[d]]=b}function k(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||ha)-(~a.sourceIndex||ha);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function l(a){return function(b){return"input"===b.nodeName.toLowerCase()&&
b.type===a}}function n(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function p(a){return f(function(b){b=+b;return f(function(c,d){for(var f,e=a([],c.length,b),g=e.length;g--;)if(c[f=e[g]])c[f]=!(d[f]=c[f])})})}function I(a){return a&&typeof a.getElementsByTagName!==S&&a}function x(){}function w(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function D(a,b,c){var d=b.dir,f=c&&"parentNode"===d,e=qa++;return b.first?function(b,c,
e){for(;b=b[d];)if(1===b.nodeType||f)return a(b,c,e)}:function(b,c,g){var Y,h,ca=[F,e];if(g)for(;b=b[d];){if((1===b.nodeType||f)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||f){h=b[z]||(b[z]={});if((Y=h[d])&&Y[0]===F&&Y[1]===e)return ca[2]=Y[2];h[d]=ca;if(ca[2]=a(b,c,g))return!0}}}function t(a){return 1<a.length?function(b,c,d){for(var f=a.length;f--;)if(!a[f](b,c,d))return!1;return!0}:a[0]}function q(a,b,c,d,f){for(var e,g=[],h=0,k=a.length,m=null!=b;h<k;h++)if(e=a[h])if(!c||c(e,d,f))g.push(e),
m&&b.push(h);return g}function s(a,b,d,e,g,h){e&&!e[z]&&(e=s(e));g&&!g[z]&&(g=s(g,h));return f(function(f,h,k,m){var n,p,x=[],D=[],l=h.length,w;if(!(w=f)){w=b||"*";for(var t=k.nodeType?[k]:k,I=[],R=0,s=t.length;R<s;R++)c(w,t[R],I);w=I}w=a&&(f||!b)?q(w,x,a,k,m):w;t=d?g||(f?a:l||e)?[]:h:w;d&&d(w,t,k,m);if(e){n=q(t,D);e(n,[],k,m);for(k=n.length;k--;)if(p=n[k])t[D[k]]=!(w[D[k]]=p)}if(f){if(g||a){if(g){n=[];for(k=t.length;k--;)if(p=t[k])n.push(w[k]=p);g(null,t=[],n,m)}for(k=t.length;k--;)if((p=t[k])&&
-1<(n=g?P.call(f,p):x[k]))f[n]=!(h[n]=p)}}else t=q(t===h?t.splice(l,t.length):t),g?g(null,h,t,m):M.apply(h,t)})}function v(a){var b,c,d,f=a.length,e=u.relative[a[0].type];c=e||u.relative[" "];for(var g=e?1:0,h=D(function(a){return a===b},c,!0),k=D(function(a){return-1<P.call(b,a)},c,!0),m=[function(a,c,d){return!e&&(d||c!==$)||((b=c).nodeType?h(a,c,d):k(a,c,d))}];g<f;g++)if(c=u.relative[a[g].type])m=[D(t(m),c)];else{c=u.filter[a[g].type].apply(null,a[g].matches);if(c[z]){for(d=++g;d<f&&!u.relative[a[d].type];d++);
return s(1<g&&t(m),1<g&&w(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(Z,"$1"),c,g<d&&v(a.slice(g,d)),d<f&&v(a=a.slice(d)),d<f&&w(a))}m.push(c)}return t(m)}function ra(a,b){var d=0<b.length,e=0<a.length,g=function(f,g,h,k,m){var n,p,w,t=0,x="0",D=f&&[],l=[],I=$,R=f||e&&u.find.TAG("*",m),s=F+=null==I?1:Math.random()||0.1,na=R.length;for(m&&($=g!==B&&g);x!==na&&null!=(n=R[x]);x++){if(e&&n){for(p=0;w=a[p++];)if(w(n,g,h)){k.push(n);break}m&&(F=s)}d&&((n=!w&&n)&&t--,f&&D.push(n))}t+=
x;if(d&&x!==t){for(p=0;w=b[p++];)w(D,l,g,h);if(f){if(0<t)for(;x--;)!D[x]&&!l[x]&&(l[x]=sa.call(k));l=q(l)}M.apply(k,l);m&&(!f&&0<l.length&&1<t+b.length)&&c.uniqueSort(k)}m&&(F=s,$=I);return D};return d?f(g):g}var T,y,u,A,ia,W,ea,ga,$,N,U,L,B,H,G,C,Q,aa,V,z="sizzle"+-new Date,E=a.document,F=0,qa=0,ja=d(),ka=d(),la=d(),fa=function(a,b){a===b&&(U=!0);return 0},S="undefined",ha=-2147483648,ta={}.hasOwnProperty,O=[],sa=O.pop,ua=O.push,M=O.push,ma=O.slice,P=O.indexOf||function(a){for(var b=0,c=this.length;b<
c;b++)if(this[b]===a)return b;return-1},Z=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,va=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,wa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,xa=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,ya=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
za=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ba={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Aa=/^(?:input|select|textarea|button)$/i,Ba=/^h\d$/i,X=/^[^{]+\{\s*\[native \w/,oa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,pa=/'|\\/g,J=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,K=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{M.apply(O=ma.call(E.childNodes),E.childNodes),O[E.childNodes.length].nodeType}catch(Ca){M={apply:O.length?function(a,b){ua.apply(a,ma.call(b))}:function(a,b){for(var c=
a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}y=c.support={};ia=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};L=c.setDocument=function(a){var b=a?a.ownerDocument||a:E;a=b.defaultView;if(b===B||9!==b.nodeType||!b.documentElement)return B;B=b;H=b.documentElement;G=!ia(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){L()},!1):a.attachEvent&&a.attachEvent("onunload",function(){L()}));y.attributes=e(function(a){a.className="i";return!a.getAttribute("className")});
y.getElementsByTagName=e(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});y.getElementsByClassName=X.test(b.getElementsByClassName)&&e(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});y.getById=e(function(a){H.appendChild(a).id=z;return!b.getElementsByName||!b.getElementsByName(z).length});y.getById?(u.find.ID=function(a,b){if(typeof b.getElementById!==S&&G){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},u.filter.ID=function(a){var b=a.replace(J,K);return function(a){return a.getAttribute("id")===b}}):(delete u.find.ID,u.filter.ID=function(a){var b=a.replace(J,K);return function(a){return(a=typeof a.getAttributeNode!==S&&a.getAttributeNode("id"))&&a.value===b}});u.find.TAG=y.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==S)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],f=0,e=b.getElementsByTagName(a);if("*"===a){for(;c=
e[f++];)1===c.nodeType&&d.push(c);return d}return e};u.find.CLASS=y.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==S&&G)return b.getElementsByClassName(a)};Q=[];C=[];if(y.qsa=X.test(b.querySelectorAll))e(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&C.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||C.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||C.push(":checked")}),e(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&C.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||C.push(":enabled",":disabled");a.querySelectorAll("*,:x");C.push(",.*:")});(y.matchesSelector=X.test(aa=H.matches||H.webkitMatchesSelector||H.mozMatchesSelector||H.oMatchesSelector||H.msMatchesSelector))&&
e(function(a){y.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");Q.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});C=C.length&&RegExp(C.join("|"));Q=Q.length&&RegExp(Q.join("|"));
V=(a=X.test(H.compareDocumentPosition))||X.test(H.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};fa=a?function(a,c){if(a===c)return U=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):
1;return d&1||!y.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===E&&V(E,a)?-1:c===b||c.ownerDocument===E&&V(E,c)?1:N?P.call(N,a)-P.call(N,c):0:d&4?-1:1}:function(a,c){if(a===c)return U=!0,0;var d,f=0;d=a.parentNode;var e=c.parentNode,g=[a],h=[c];if(!d||!e)return a===b?-1:c===b?1:d?-1:e?1:N?P.call(N,a)-P.call(N,c):0;if(d===e)return k(a,c);for(d=a;d=d.parentNode;)g.unshift(d);for(d=c;d=d.parentNode;)h.unshift(d);for(;g[f]===h[f];)f++;return f?k(g[f],h[f]):g[f]===E?-1:h[f]===
E?1:0};return b};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==B&&L(a);b=b.replace(xa,"='$1']");if(y.matchesSelector&&G&&(!Q||!Q.test(b))&&(!C||!C.test(b)))try{var d=aa.call(a,b);if(d||y.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(f){}return 0<c(b,B,null,[a]).length};c.contains=function(a,b){(a.ownerDocument||a)!==B&&L(a);return V(a,b)};c.attr=function(a,b){(a.ownerDocument||a)!==B&&L(a);var c=u.attrHandle[b.toLowerCase()],
c=c&&ta.call(u.attrHandle,b.toLowerCase())?c(a,b,!G):void 0;return void 0!==c?c:y.attributes||!G?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var b,c=[],d=0,f=0;U=!y.detectDuplicates;N=!y.sortStable&&a.slice(0);a.sort(fa);if(U){for(;b=a[f++];)b===a[f]&&(d=c.push(f));for(;d--;)a.splice(c[d],1)}N=null;return a};A=c.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===
b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=A(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=A(b);return c};u=c.selectors={cacheLength:50,createPseudo:f,match:ba,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(J,K);a[3]=(a[3]||a[4]||a[5]||"").replace(J,K);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ba.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(c&&ya.test(c)&&(b=W(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=
a.replace(J,K).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ja[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ja(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==S&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(f){f=c.attr(f,a);if(null==f)return"!="===b;if(!b)return!0;f+="";return"="===b?f===d:"!="===b?
f!==d:"^="===b?d&&0===f.indexOf(d):"*="===b?d&&-1<f.indexOf(d):"$="===b?d&&f.slice(-d.length)===d:"~="===b?-1<(" "+f+" ").indexOf(d):"|="===b?f===d||f.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,f){var e="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===f?function(a){return!!a.parentNode}:function(b,c,k){var m,n,p,w,x;c=e!==g?"nextSibling":"previousSibling";var t=b.parentNode,l=h&&b.nodeName.toLowerCase();k=!k&&!h;if(t){if(e){for(;c;){for(n=b;n=n[c];)if(h?n.nodeName.toLowerCase()===
l:1===n.nodeType)return!1;x=c="only"===a&&!x&&"nextSibling"}return!0}x=[g?t.firstChild:t.lastChild];if(g&&k){k=t[z]||(t[z]={});m=k[a]||[];w=m[0]===F&&m[1];p=m[0]===F&&m[2];for(n=w&&t.childNodes[w];n=++w&&n&&n[c]||(p=w=0)||x.pop();)if(1===n.nodeType&&++p&&n===b){k[a]=[F,w,p];break}}else if(k&&(m=(b[z]||(b[z]={}))[a])&&m[0]===F)p=m[1];else for(;n=++w&&n&&n[c]||(p=w=0)||x.pop();)if((h?n.nodeName.toLowerCase()===l:1===n.nodeType)&&++p)if(k&&((n[z]||(n[z]={}))[a]=[F,p]),n===b)break;p-=f;return p===d||
0===p%d&&0<=p/d}}},PSEUDO:function(a,b){var d,e=u.pseudos[a]||u.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return e[z]?e(b):1<e.length?(d=[a,a,"",b],u.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var d,f=e(a,b),g=f.length;g--;)d=P.call(a,f[g]),a[d]=!(c[d]=f[g])}):function(a){return e(a,0,d)}):e}},pseudos:{not:f(function(a){var b=[],c=[],d=ea(a.replace(Z,"$1"));return d[z]?f(function(a,b,c,f){f=d(a,null,f,[]);for(var e=a.length;e--;)if(c=f[e])a[e]=!(b[e]=c)}):
function(a,f,e){b[0]=a;d(b,null,e,c);return!c.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){a=a.replace(J,K);return function(b){return-1<(b.textContent||b.innerText||A(b)).indexOf(a)}}),lang:f(function(a){za.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(J,K).toLowerCase();return function(b){var c;do if(c=G?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(c){var d=a.location&&a.location.hash;return d&&d.slice(1)===c.id},root:function(a){return a===H},focus:function(a){return a===B.activeElement&&(!B.hasFocus||B.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!u.pseudos.empty(a)},header:function(a){return Ba.test(a.nodeName)},input:function(a){return Aa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:p(function(){return[0]}),
last:p(function(a,b){return[b-1]}),eq:p(function(a,b,c){return[0>c?c+b:c]}),even:p(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:p(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:p(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:p(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};u.pseudos.nth=u.pseudos.eq;for(T in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})u.pseudos[T]=l(T);for(T in{submit:!0,reset:!0})u.pseudos[T]=n(T);x.prototype=u.filters=
u.pseudos;u.setFilters=new x;W=c.tokenize=function(a,b){var d,f,e,g,h,k,n;if(h=ka[a+" "])return b?0:h.slice(0);h=a;k=[];for(n=u.preFilter;h;){if(!d||(f=va.exec(h)))f&&(h=h.slice(f[0].length)||h),k.push(e=[]);d=!1;if(f=wa.exec(h))d=f.shift(),e.push({value:d,type:f[0].replace(Z," ")}),h=h.slice(d.length);for(g in u.filter)if((f=ba[g].exec(h))&&(!n[g]||(f=n[g](f))))d=f.shift(),e.push({value:d,type:g,matches:f}),h=h.slice(d.length);if(!d)break}return b?h.length:h?c.error(a):ka(a,k).slice(0)};ea=c.compile=
function(a,b){var c,d=[],f=[],e=la[a+" "];if(!e){b||(b=W(a));for(c=b.length;c--;)e=v(b[c]),e[z]?d.push(e):f.push(e);e=la(a,ra(f,d));e.selector=a}return e};ga=c.select=function(a,b,c,d){var f,e,g,h,k="function"===typeof a&&a,n=!d&&W(a=k.selector||a);c=c||[];if(1===n.length){e=n[0]=n[0].slice(0);if(2<e.length&&"ID"===(g=e[0]).type&&y.getById&&9===b.nodeType&&G&&u.relative[e[1].type]){if(b=(u.find.ID(g.matches[0].replace(J,K),b)||[])[0])k&&(b=b.parentNode);else return c;a=a.slice(e.shift().value.length)}for(f=
ba.needsContext.test(a)?0:e.length;f--;){g=e[f];if(u.relative[h=g.type])break;if(h=u.find[h])if(d=h(g.matches[0].replace(J,K),da.test(e[0].type)&&I(b.parentNode)||b)){e.splice(f,1);a=d.length&&w(e);if(!a)return M.apply(c,d),c;break}}}(k||ea(a,n))(d,b,!G,c,da.test(a)&&I(b.parentNode)||b);return c};y.sortStable=z.split("").sort(fa).join("")===z;y.detectDuplicates=!!U;L();y.sortDetached=e(function(a){return a.compareDocumentPosition(B.createElement("div"))&1});e(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||h("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!y.attributes||!e(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&h("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});e(function(a){return null==a.getAttribute("disabled")})||h("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof r&&r.amd?r(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);a.browser=function(){var b,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);a.each(d,function(a){b=(/[\/ :]([^\/ :]+)$/.exec(a)||[])[1];c[b?a.substr(0,a.length-b.length-
1).replace(/\d*$/,""):a]=b||!0});return{aol:c.aol,blackberry:c.blackberry,firefox:c.firefox,ie:Boolean(c.msie||c.trident),ios:Boolean(c.applewebkit&&c.mobile),opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie||c.rv||c.firefox)||!1}}();a.page=function(){var b,c=a.rootContext(window),c={description:function(){return a.map(a.select("meta[name='description' i]").slice(0,1),function(a){return a.getAttribute("content")})[0]}(),font_size:function(){var b=a.css(document.body,
"font-size");if(b)return parseFloat(b)}(),referrer:c.document.referrer,title:c.document.title};for(b in c)c[b]=c[b]||null;return c}();a.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};a.harmony.DEFAULT=0;a.pii=function(){var b={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,b){return this.regexp(b).test(a)},redact:function(a,b){return a.replace(this.regexp(b),"___")},
regexp:function(c){c=a.extend({},c);var f=a.map(a.all(b,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+f.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,b){return this.contains(a+" "+document.referrer,b||{numeric:!1})}};return{contains:a.bind(c.contains,c),redact:a.bind(c.redact,c),transmits:a.bind(c.transmits,c)}}();a.platforms=function(){var b={NONE:{id:"full",scope:"body",spec:{selector:"body"}},bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},
scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{spec:{parser:/^post_message_(\d+)$/,
selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},c={getPostId:function(b){var c,e;if(this===
a.platforms.NONE)return" ";e=this.spec.parse_el?a.select(this.spec.parse_el,b)[0]:b;a.find(this.spec.attributes||["id"],a.bind(function(a){c=e[a]?e[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(b){var c=[];a.each(this.getPosts(b),a.bind(function(b){(b=this.getPostId(b))&&!a.contains(c,b)&&c.push(b)},this));return c.length?c:null},getPosts:function(b){var c=[];!b&&(document&&document.body)&&(b=[document.body]);b&&this.spec&&(c=a.withScope(b,this.spec.selector,
{consolidate:!0}));return c}};a.each(b,function(d,f){d.id=d.id||f;a.each(c,function(b,c){d[c]=a.bind(b,d)});b[f]=d});b.DEFAULT_POST_ID=" ";b.findById=function(b){return a.find(a.platforms,function(a){return a.id===b})};return b}();a.observer=function(){var b,c=[],d=0,f=function(){b||(b=new MutationObserver(a.entryPoint(function(b){var d=[];a.each(b,function(b){var c=[];"characterData"===b.type?b.target&&(c=[b.target]):"attributes"===b.type?c=[b.target]:b.addedNodes&&b.addedNodes.length&&(c=a.toArray(b.addedNodes));
c.length&&(d=d.concat(c))});0<d.length&&a.each(c,function(a){a.callback(d)})})))},e=function(c){var e={attributes:!1,characterData:!1,childList:!1,subtree:!0};d||(f(),c.opts.attributes&&(e=a.extend(e,{attributes:!0}),"array"===a.type(c.opts.attributes)&&(e=a.extend(e,{attributeFilter:c.opts.attributes}))),c.opts.content&&(e=a.extend(e,{characterData:!0,childList:!0})),b.observe(c.context,e))};return{start:function(b,d,f){b.document&&(b=b.document);d=a.extend({attributes:!1,content:!0},d);a.traits.mutation&&
a.contains(["document","element"],a.type(b))&&(b={callback:f,context:b,opts:d},c.push(b),e(b))},pause:function(){d++;b&&b.disconnect()},resume:function(){d--;a.each(c,e)}}}();a.traits={basicCompatibility:!(a.browser.blackberry||a.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!a.browser.ios,fastRegexp:!a.browser.firefox,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:a.browser.aol||
!(a.browser.ie||a.browser.opera),mutation:window.MutationObserver&&!a.browser.ie,performanceTimingApi:Boolean(window.performance&&window.performance.mark&&window.performance.measure&&window.performance.now&&window.performance.getEntriesByName),performanceNavigationTiming:Boolean(window.performance&&window.performance.getEntriesByType&&window.performance.getEntriesByType("navigation")&&window.performance.getEntriesByType("navigation")[0]&&window.performance.getEntriesByType("navigation")[0].domInteractive),
referrerPolicy:!a.browser.ie,quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var k,q,s,v;e={EVENT_LEVEL_LINK:1,EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:function(){var b;return function(){b||(b=a.generateNodeFilter({classes:["novig"],rels:["novig"],selectors:k.exclude_scope,tags:"applet embed noscript object head img input link meta param select button iframe option script style svg textarea title".split(" ")}));return b.apply(e,
arguments)}}(),api:function(){var b,c,d,f=function(){var b={optimize:"content",domains:"content"};return function(c,d,f){var e=a.toArray(arguments).slice(3,arguments.length),g=b[c];Boolean(g)&&(f=a.extend({},f,{json_payload:g}));var g=c,m=h(f),l;l=a.extend(a.commonParams(c,k),d);l.subId&&l.key!==k.key&&(l.subId=null);return{data:e,method:g,opts:m,params:l}}}(),e=function(b){var c={},d={};a.each(b,function(b){var f=b[0],e=b[1],g=b[2]||{};b=a.toArray(b).slice(3,b.length);d[f]=a.mergeParams(d[f]||a.commonParams(f,
k),e);c[f]=c[f]||[];c[f].push({data:b,opts:h(g)})});return{calls:c,params:d}},h=function(b){b=b||{};"function"===a.type(b.fn)&&(b.fn=function(c){return function(d){var f,e=d.response?d.response[0]:null;"object"===a.type(e)&&("array"===a.type(e.crawl)&&"object"===a.type(v.crawler)&&"function"===a.type(v.crawler.crawl))&&(f=a.map(e.crawl,function(a){return a+""}),delete e.crawl,v.crawler.crawl(f));return c.apply(b,arguments)}}(b.fn));return b},m=function(b){var c=b.opts.base_url||k.api_url,d=b.opts.path||
"/"+b.method;delete b.opts.base_url;return a.request.apply(a,[c+d,b.params,b.opts].concat(b.data))},l=function(b,c,d){a.each(c,function(c){c&&(c.opts&&c.opts.fn&&b)&&c.opts.fn({response:a.packageArgs(b),data:c.data,args:d})})};b=function(){var b=function(b){var c=b.data[0].params,d=b.data[0].calls;b=a.fromJSON(b.response[0])||{};a.each(b,function(b,f){var e=c[f],g=d[f],h;if("string"===a.type(b)&&(h=b.match(/^[^(]+\((.*)\);?\s*$/)))b=a.fromJSON(h[1]);l(b,g,e)})};return function(c){c=e(c,!0);m({data:c,
method:"batch",params:a.extend(a.commonParams("batch",k),c.params),opts:{json_payload:"batch",jsonp:!1,fn:a.bind(b,window)}})}}();c=function(b,c,d){var h=e(b,!1);b=a.reduce({},h.calls[d],function(a,b){return{jsonp:a.jsonp||!b.opts||!1!==b.opts.jsonp,ssl:a.ssl||!b.opts||!1!==b.opts.ssl}});return m(f(c,h.params[c],{fn:function(a){l(a.response[0],h.calls[c],h.params[c])},jsonp:b.jsonp,ssl:b.ssl},h))};d=function(){return m(f.apply(this,arguments))};return a.batchable(function(){var f,e;return a.batched(arguments)?
(f=a.batchArgs(arguments),e=a.batchCallType(f),"batch"===e?b.call(this,f):c.call(this,f,e)):d.apply(this,arguments)},function(){return{batch:k.batch_calls,timeout:k.batch_call_timeout}})}(),addEventListener:function(a,c){this.fire(a,c)},click:function(){var b=function(b,c){if("_self"===c)return b;if(a.traits.crossWindowCommunication&&a.traits.jsRedirectSetsReferrer){var e=b.open("",c);e.focus();return e}},c=function(b){var c=b.previousSibling,g=b.nextSibling,h=["",b.textContent,""],k=function(a,b){for(var c=
a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},l=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==h[1]&&(h[0]=c&&3===c.nodeType?k(c,"previous"):"",h[2]=g&&3===g.nodeType?k(g,"next"):"",h=l.apply(this,h),""!==
h[0]&&""!==h[2]&&(h[0]=h[0].split(" ").reverse().slice(0,10+(" "===h[0].substr(h[0].length-1,1)?1:0)).reverse().join(" "),h[2]=h[2].split(" ").slice(0,10).join(" "),b={type:"context",itype:(a.cache(b,"params")||{}).type,before:h[0],after:h[2],txt:h[1],loc:window.document.location.href,out:a.getActualHref(b),v:2},e.log("info",a.toQuery(b))))};return function(d,f){var e,h,m,l,n={},p=a.context(d)||window;f=d.target||f;f=!f||f===p.name||"_top"===f&&p.top===p||"_parent"===f&&p.parent===p?"_self":f;m=b(p,
f);if("_self"!==f&&(!a.traits.crossWindowCommunication||!a.traits.jsRedirectSetsReferrer))l="go";else try{if(void 0===m.document)throw!0;l="jsonp"}catch(q){l="go"}e=a.destructing(a.apiCallback(function(){this.eventTimer.stop("clk");var b=a.toArray(arguments);b.unshift(d,m,f);this.onApiClick.apply(this,b)},this));a.cache(this,"link","string"===typeof d?d:a.getActualHref(d));if("string"===typeof d&&(d=a.createA(d,f),!this.processLink(d))||!k.enabled)return e();!a.traits.referrerPolicy&&this.isPrivate(d)&&
(l="go");h=this.clickParams(d,l);this.eventTimer.start("clk");k.log_context&&c(d);if("go"===l)h=this.redirectUrl(h,n),this.redirect(h,p,m,f);else if(m===p)this.api.now("click",h,a.extend(n,{fn:e,timeout:k.click_timeout}));else{if(a.contextIsAncestor(p,m))return this.redirect(a.getActualHref(d),p,m,f);e=a.entryPoint(e);setTimeout(function(){e()},k.click_timeout);m.document.open();m.callback=e;m.document.write("<html><head><title>"+a.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",
h,a.extend(n,{fn:"callback","return":!0}))+'">\x3c/script></head></html>');m.document.close()}}}(),clickParams:function(b,c){var d=a.extend(a.cache(b,"params"),a.cache("opt_params"),{format:c,out:a.getActualHref(b),reaf:k.reaffiliate||null,ref:a.page.referrer||null,rewrit:a.cache(b,"rewrit"),title:a.page.title,txt:b.innerHTML});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},detectFiltering:function(){var b;try{b={},b=new function(){this.detect=
function(a,b){function c(a,b){0==l||1E3<b?a(0==l&&k):setTimeout(function(){c(a,2*b)},2*b)}function e(){--l||(k=!n&&p)}var k=!1,l=2,n=!1,p=!1;if("function"==typeof b){a+="?ch=*&rn=*";var q=11*Math.random(),x=new Image;x.onload=e;x.onerror=function(){n=!0;e()};x.src=a.replace(/\*/,1).replace(/\*/,q);x=new Image;x.onload=e;x.onerror=function(){p=!0;e()};x.src=a.replace(/\*/,2).replace(/\*/,q);c(b,250)}}}}catch(c){b={detect:function(a,b){b(!0)}}}return function(c){var e=a.updateUrl(k.asset_url,{pathname:"/images/pixel.gif"});
b.detect(e,c)}}(),enabled:function(){if(k.enabled&&s!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))k.enabled=!1;return k.enabled},expose:function(){return function(b,c){if((c=c||this[b])&&!v[b]){var d=v,f;f=c;f="function"===a.type(f)?a.entryPoint(a.bind(f,e)):f;d[b]=f}}}(),fire:function(){var b={};return function(c,d){c=c.toLowerCase();var e=b[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=
!0,a.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);b[c]=e}}(),handleRightClick:function(b,c){if(k.rewrite_modified&&b&&c)switch(c){case "setup":a.cache(b,"href")||a.cache(b,"href",b.href);b.href=this.redirectUrl(this.clickParams(b,"go"));setTimeout(a.entryPoint(a.bind(function(){this.handleRightClick(b,"teardown")},this)),0);break;case "teardown":a.cache(b,"href")&&(b.href=a.cache(b,"href"))}},harmony:function(a){return k.harmony_level<=a},init:function(){var b=
function(){var b=a.rootContext(window),d=!0===b.__v5k;b.__v5k=!0;return!d};return function(){var c=this;q={};if(b()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(d){}a.exceptionLogger(a.bind(c.logException,c),!k.dev);a.each(k.script_timeout);return a.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var b,c={};if(window.vglnk)for(b in window.vglnk)"_plugin"===b.substr(-7)&&(c[b]=window.vglnk[b]);
v=s[l]=a.noop;this.expose("click");this.expose("link",a.bind(function(b){"element"===a.type(b)&&b.href&&(this.initContext(a.context(b)),this.processLink(b))},this));this.expose("open",a.bind(this.click,this));this.expose("$",a.clone(a));this.expose("allowed");this.expose("api");this.expose("apiNow",a.bind(this.api.now,this.api));this.expose("harmony");this.expose("isBlacklisted");this.expose("isCommercial");this.expose("initLinks");this.expose("opt");this.expose("platform");this.expose("sendLinks");
this.expose("clickParams",function(){return a.extend(a.commonParams("click",k),e.clickParams.apply(e,arguments))});this.expose("registerProcessor",function(){if(0<arguments.length)return e.registerProcessor.apply(e,arguments)});a.extend(v,v===window.vglnk?c:{})},initContext:function(){var b=[];return function(c){if(void 0===c)return b;c&&!a.contains(b,c)&&(b.push(c),this.initLinks(c),this.initEvents(c))}}(),initDomObserver:function(b,c){a.observer.start(b,c,a.batchable(function(b){a.batched(arguments)&&
(b=a.reduce([],a.batchArgs(arguments,0),function(a,b){return a.concat(b)}));b=a.all(a.unique(b),function(a){return Boolean(a.parentNode)&&e.allowed(a)});0<b.length&&(e.processLinks(a.links(b)),a.each(q,function(a,c){a.opts.mode!==e.PLUGIN_MANUAL&&e.runPlugin(c,b)}))},function(){return{batch:k.batch_mutation,timeout:k.batch_mutation_timeout}}))},initDRApi:function(){var b=!1;window.DrivingRevenue=a.entryPoint(a.destructing(a.bind(function(){b=!0;k.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));
a.on("DOMReady",function(){if(!b)try{delete window.DrivingRevenue}catch(a){window.DrivingRevenue=void 0}})},initEvents:function(b){var c=a.traits.windowLevelHandlers?b:b.document,d=function(c){c=c||b.event;if((c=a.eventLink(c))&&!a.cache(c,"evented"))g(e.EVENT_LEVEL_LINK,c),a.cache(c,"evented",!0)},f=function(b,c){return function(){var d=[b].concat(a.toArray(arguments));c.apply(e,d)}},g=function(b,c){a.on(c,"click",f(b,e.onClick));a.on(c,"contextmenu",f(b,e.onContextmenu))};if(k.dynamic)a.on("DOMReady",
function(){e.initDomObserver(b);k.dynamic_scope&&a.each(a.select(k.dynamic_scope,b.document),function(a){e.initDomObserver(a,{attributes:["class","id","style"],content:!1})})});a.on(c,"copy",a.bind(e.onCopy,e));a.on(c,"mousedown",d);a.on("DOMReady",function(){a.each(b.document.links,function(b){a.on(b,"mousedown",d)})});(!a.traits.quirksMode||e.harmony(a.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&g(e.EVENT_LEVEL_TOP,c)},initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",
vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==window[a]&&(v[c[a]]=window[a],"vglnk_domain"===a&&(v[c[a]]+="/api"))},initLegacyCallbacks:function(){var b,c={vl_cB:a.bind(this.onApiClick,this),vl_disable:function(){k.enabled=!1}};for(b in c)window[b]=c[b]},initLibEvents:function(){a.on(e);a.ready(a.bind(function(){this.fire("DOMReady")},this))},initLinks:function(b){var c=a.bind(function(b){this.processLinks(a.toArray(b.document.links))},this);void 0===b?
a.each(this.initContext(),c):c(b)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,c=l.split("."),d;for(l=c.pop();0<c.length;)d=c.shift(),a[d]=a[d]||{},a=a[d];s=a;v=s[l]=s[l]||{}},initOptions:function(){var b;this.initLegacyOptions();k=a.extend(this.publicOptions({anywhere_url:"//redirect.viglink.com",api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:a.traits.basicCompatibility,key:null,link_urls:!0,partner:null,
platform:a.platforms.NONE.id,reaffiliate:!1,sub_id:null,sync_url:"//api.viglink.com/api",blacklist_domains:null,commercial_domains:null,harmony_level:a.harmony.DEFAULT,link_target:null,private_domains:null,rewrite_any:!0,rewrite_modified:!1,rewrite_original:!0}),k,v,{batch_calls:!0,batch_call_timeout:100,batch_links:!1,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,debug:!1,debug_performance:!1,declare_handler:!1,dynamic:!0,dynamic_scope:null,exclude_scope:null,hop_timeout:2E3,insert_host:"i.viglink.com",
library_id:null,links_merge_timeout:75,links_version:"3.2",log_context:!0,nofollow:{},norewrite:{},script_timeout:2E3,testing_js:[],time:!1,time_log_timeout:3E3,plugins:{crawler:{},harmony:{},link_affiliation:{},modified_clicks:{}}});k.sync_url=k.sync_url||k.api_url;for(b in k)"_plugin"===b.substr(-7)&&delete k[b]},initPlugins:function(){var b,c=1,d={link_affiliation:"convert",link_optimization:"optimize",page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},
f=["spotlight"],g=["harmony"],h=function(a){return function(a){return function(){delete q[a].opts.mode;c=1;clearTimeout(b);s()}}(a)},l=function(b){var c;a.find(d,function(a,b){return"insert"===a&&(c=b)});b[c]||(b[c]={enabled:!0,key:k.key,link_phrases:!1});b[c].link_urls=k.link_urls;return b},s=function(){var d={_ran:!1,init:a.noop,initDocuments:a.noop,initNodes:a.noop,"public":{}},f=function(b,c){b.setup=b.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===a.type(b.setup)&&(Boolean(b.initDocuments)||
(b=a.extend(b,d,b.setup(a.reformatKeys(b.opts),a.clone(a),v,h(k.key))),b["public"]&&e.expose(c,b["public"],!1)),b.opts.mode!==e.PLUGIN_MANUAL&&e.runPlugin(c))},h=function(b){var c=function(){if(b){var c=a.toArray(arguments);c.unshift("custom",b);e.log.apply(this,c)}};c.eventTimer=e.eventTimer;return c},l=function(a){return!Boolean(a._ran)};b=null;a.each(g,function(a){var b=q[a];b&&!Boolean(b._ran)&&f(b,a)});a.each(a.all(q,l),f);a.find(q,l)&&(b=setTimeout(a.entryPoint(s),Math.min(Math.max(Math.pow(2,
++c),100),5E3)))},n=function(){setTimeout(function(){e.api.flush()},100);s();a.on("DOMReady",function(){setTimeout(e.api.flush,0)})};return function(b){b=l(b);a.each(b,a.bind(function(b,c){c=d[c]||c;"object"===typeof b&&!1!==b.enabled&&(q[c]={opts:b},a.contains(f,c)&&a.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),b.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,h(c)))},this));n()}}(),initProcessors:function(){this.registerProcessor(function(b){var c;c=a.createA(k.api_url);if("/api/click"===
b.pathname&&(b.hostname===c.hostname||b.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=a.fromQuery(b.search),void 0!==c.out&&(b.href=c.out,delete c.out,a.cache(b,"params",c))});this.registerProcessor(function(b){k.nofollow[b.href]&&!a.hasRel(b,"nofollow")&&(b.rel=(b.rel?b.rel+" ":"")+"nofollow")});this.registerProcessor(function(b){k.declare_handler&&a.attributes(b,{"data-hl":"viglink"})});this.registerProcessor(function(b){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&
a.hasRel(b,"external"))&&(b.rel=b.rel.replace(/(^| )external( |$)/,""),b.target="_blank")});this.registerProcessor(function(){a.each(a.select(".vl_disclosure"),function(b){var c,d;c=a.createEl(b.tagName,{height:0,visibility:"hidden"});document.body.appendChild(c);d=a.css(c,"display");document.body.removeChild(c);a.css(b,{display:d})})})},isAuctionLink:function(b){return!0===a.cache(b,"auctioned")},isBlacklisted:function(b){return"object"===a.type(k.blacklist_domains)&&k.blacklist_domains[a.canonicalizeHostname(b)]},
isCommercial:function(b){return this.loadedCommercial()&&k.commercial_domains[a.canonicalizeHostname(b)]},isPrivate:function(b){if("array"!==a.type(k.private_domains))return!1;var c=a.canonicalizeHostname(b);return a.find(k.private_domains,function(b){return RegExp("(^|\\.)"+a.escapeRegExp(b)+"$","i").test(c)})},isRewritable:function(){var b=a.canonicalizeHostname(document.location),c=a.generateNodeFilter({classes:["norewrite"],rels:["norewrite","noskim"],custom:function(c,f){if(!f)return!1;var g=
a.canonicalizeHostname(c),h="",l=!1;try{h=c.protocol,g.charAt(0)}catch(q){return!0}l=Boolean(""===g||!h.match(/^https?:$/i)||k.norewrite[g]);if(h=!l)var h=a.cache(c,"type"),n=a.cache(c,"params")||{},h=!Boolean(h||n.type);h&&(l=Boolean(b===g||!k.rewrite_original||!k.rewrite_any&&!e.isCommercial(c)));return l}});return function(a){return c(a)}}(),loadedCommercial:function(){return"object"===a.type(k.commercial_domains)},log:function(b,c,d,e){var g,h=a.toQuery({libId:k.library_id,nocache:a.uniqid()});
g="pixel.gif";if("custom"===b)h+="&"+a.toQuery({key:c,type:d}),a.each("array"===a.type(e)?e:[e],function(b){a.each(["e","i","o"],function(a){delete b[a]});h+="&"+a.toQuery(b)});else{h+="&"+a.toQuery({key:k.key,drKey:k.key?null:k.dr_key,subId:k.sub_id});if("time"===b&&a.traits.json)g="time.gif",b={e:a.toJSON(c),v:2};else if("exception"===b)b={e:c,o:d};else if("info"===b)b={i:c};else return;h+="&"+a.toQuery(b)}g=k.api_url+"/"+g+"?"+h;a.pii.transmits(g)||(a.createEl("img").src=g)},eventTimer:function(){var b,
c,d=!1,f={},g=function(b,c){return function(){if(a.traits[c])return b.apply(this,arguments)}},h=function(b,c){return function(){if(a.reduce(!1,c,function(a,b){return a||k[b]}))return b.apply(this,arguments)}},l=a.batchable(function(){var b;b=a.batched(arguments)?a.batchArgs(arguments):[arguments];b=a.map(b,function(b){return a.prune({event:b[0],time:b[1],total:b[2]})});b.length&&e.log("time",b)},function(){return{timeout:k.time_log_timeout}}),q=h(l,["time"]),l=function(a){window.performance.mark("viglink-"+
a+"-start")};b=a.traits.performanceNavigationTiming?window.performance.getEntriesByType("navigation")[0].domInteractive:0;a.traits.performanceTimingApi&&(c=window.performance.now());return{force:g(l,"performanceTimingApi"),start:g(h(l,["debug_performance","time"]),"performanceTimingApi"),stop:g(h(function(e,g){var h,k=f[e]||0;h="viglink-"+e;var l="viglink-"+e+"-start",m="viglink-"+e+"-stop";window.performance.mark(m);window.performance.measure(h,l,m);h=window.performance.getEntriesByName(h,"measure");
h=h.slice(k);f[e]=k+h.length;g||a.each(h,function(a){q(e,a.duration,a.startTime-b)});d||(d=!0,q("load",c-b,c-b))},["debug_performance","time"]),"performanceTimingApi")}}(),logException:function(b){if(k.debug){var c={link:a.cache(this,"link"),loc:window.document.location.href,UA:navigator.userAgent};"string"===typeof b?c.message=b:c=a.extend(c,b);this.log("exception",b,a.toQuery(c))}},onApiClick:function(b,c,d,e,g){var h=e||a.getActualHref(b),l=a.bind(function(){this.redirect(h,a.context(b),c,d)},
this);"object"===typeof g&&(g.tracking||g.image)?(e=a.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(a.entryPoint(l),g.timeout||k.hop_timeout)):l()},onApiPing:function(b,c,d,f,g,h){k.rewrite_original=!1;g=a.reformatKeys(g||{});var l,q,n;f=function(b){var c={},d=function(b){a.isArray(b)?c[b[0]]=b[1]:c[b]=1};a.isArray(b)&&a.each(b,d);return c};a.exceptionLogger(function(){a.canonicalizeHostname(window.location).match(/(^|\.)cnn\.com$/)&&
(k.exclude_scope="#optanon,.OUTBRAIN,*[class*=outbrain],*[class*=partner],*[class*=sponsored]")})();a.exceptionLogger(function(){a.canonicalizeHostname(window.location).match(/^(www\.)?msn\.com$/)&&(k.dynamic_scope=".gallery-container > .gallerydata,section.gallery:first-child ~ .gallerydata",k.exclude_scope="*[class^=stb-],.sticky-footer",k.declare_handler=!0)})();q=a.extend(k.plugins,g.plugins);k=a.extend(k,g);delete k.plugins;k.click_timeout=c;k.library_id=b;this.eventTimer.stop("png");"array"===
a.type(k.testing_js)&&0<k.testing_js.length&&a.each(k.testing_js,function(b){a.jsonp(b)});a.extend(k.nofollow,f(h));a.extend(k.norewrite,f(d));for(l in k)"on"===l.toLowerCase().substr(0,2)&&(2<l.length&&"function"===a.type(k[l]))&&(a.on(e,l.toLowerCase().substr(2),a.bind(k[l],window)),delete k[l]);this.initPlugins(q);this.initContext(window);(n=a.rootContext(window))&&n!==window&&this.initContext(n);this.fire("libready")},onClick:function(b,c){c=c||window.event;var d=c.ctrlKey||c.metaKey||c.altKey||
c.shiftKey,e=c.which&&1===c.which||0===c.button,g=a.eventLink(c);if(g&&e&&!d&&!a.isDefaultPrevented(c)&&this.allowed(g)&&this.isRewritable(g)&&!this.isAuctionLink(g)&&this.shouldHandleClick(b,g))return this.click(g),a.preventDefault(c)},onContextmenu:function(b,c){var d=a.eventLink(c||window.event);d&&(this.allowed(d)&&this.isRewritable(d)&&!this.isAuctionLink(d)&&this.shouldHandleClick(b,d))&&this.handleRightClick(d,"setup")},onCopy:function(b){var c,d,f,g=[];if(window.getSelection){d=window.getSelection();
b=0;for(c=d.rangeCount;b<c;b++){try{f=d.getRangeAt(b).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(h){}0<f.length&&128>=f.length&&g.push(f)}}a.each(g,function(b){e.log("info",a.toQuery({type:"selection",txt:b,loc:location.href}))})},opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&(k[a]=c);return k[a]},ping:function(){var b=!1;return function(){if(!b&&(k.key||k.dr_key)){var c={ref:document.referrer||null,v:2};b=!0;a.pii.transmits(this.api.now("ping",c,
{"return":!0}))||(this.eventTimer.force("png"),this.detectFiltering(a.bind(function(b){b&&(k.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:a.apiCallback(this.onApiPing,this)})},this)))}}}(),platform:function(){return a.platforms.findById(k.platform)||a.platforms.NONE},processLink:function(b){var c=a.cache(b,"processors")||{},d=this.allowed(b),f=this.isRewritable(b);a.each(this.registerProcessor(),function(g){if(g.opts.any||k.rewrite_any||e.loadedCommercial()){if(!c[g.id]&&
d&&(f||g.opts.any)){var h;g.opts.scope&&"body"!==g.opts.scope&&(h=a.some([g.opts.scope+" a",g.opts.scope],function(c){return a.matches(b,c)}));!1!==h&&g.fn(b)}c[g.id]=!0}});a.cache(b,"processors",c);return b},processLinks:function(b){a.each(b,a.bind(this.processLink,this))},publicOptions:function(){var b={};return function(c){"object"===a.type(c)&&(b=c);return a.extend({},b)}}(),redirect:function(b,c,d,f){var g=function(b,c,d){var f=[],g;if(a.traits.referrerPolicy){g=function(a){var b=c.document.createElement("meta");
b.name="referrer";b.content=a;c.document.getElementsByTagName("head")[0].appendChild(b)};e.isPrivate(b)&&(f=[g("no-referrer"),g("never")]);d();try{a.each(f,function(a){a.parentNode.removeChild(a)})}catch(k){}}else d()};c=c||window.top;!a.traits.crossWindowCommunication&&!d?(f=c.open(b,f),f.focus()):a.traits.jsRedirectSetsReferrer?setTimeout(a.entryPoint(function(){!d||d===c?g(b,c,function(){c.location=b}):a.contextIsAncestor(c,d)?d.location=b:d.location.replace(b)}),0):("_blank"===f&&(f=a.uniqid("win_")),
f=a.createA(b,f),f.rel="norewrite",c.document.body.appendChild(f),f.click(),f.parentNode.removeChild(f))},redirectUrl:function(b,c){c=c||{};return this.api.now("click",b,a.extend(c,{base_url:k.anywhere_url,path:"/"},{"return":!0}))},runPlugin:function(b,c){var d=window.document,e=q[b];if(e&&e.initDocuments){if(c)e.initNodes(c);else if(e.init(),"function"===a.type(e.initDocuments)&&"document"===a.type(d)&&e.initDocuments([d]),"function"===a.type(e.initNodes)&&"element"===a.type(d.body))a.on("DOMReady",
function(){e.initNodes([d.body])});e._ran=!0}},registerProcessor:function(){var b=!1,c=[],d=function(d,e){if(void 0===d)return c;"function"===a.type(d)&&(e=a.extend({any:!1,scope:null},e),c.push({fn:d,id:a.uniqid(),opts:e}),b&&this.initLinks())};d(function(){b=!0},{any:!0});return d}(),sendLinks:a.mergeable(function(){return{batchFn:e.api,nonBatchFn:e.api.now,batchable:k.batch_links,timeout:k.links_merge_timeout}}),shouldHandleClick:function(b,c){var d=!0,e="inserted"===a.cache(c,"type");b===this.EVENT_LEVEL_LINK&&
(d=this.harmony(a.harmony.LINK_EVENTS)||(this.isCommercial(c)||e)&&this.harmony(a.harmony.COMMERCIAL_LINK_EVENTS));return d}};e.init();try{delete window.vglnk_self}catch(A){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(l,e,a){var r={},k,q;l=e.extend({any:!0,convert_minimum_bid:!1,check_exp_domains:!0},l);q={getDomains:function(){var k=[];e.each(r,function(a,e){2!==r[e]&&(k.push(e),r[e]=2)});0<k.length&&a.apiNow("domains",{domains:k.join("|"),v:"2"},{fn:e.apiCallback(q.onDomainApi,q)})},init:function(){a.opt("link_target",l.link_target);a.opt("rewrite_any",l.any);a.opt("rewrite_original",!0);(k=!l.any||a.harmony(e.harmony.COMMERCIAL_LINK_EVENTS)||l.convert_minimum_bid||l.check_exp_domains)&&
a.registerProcessor(e.bind(function(a){this.initDomainLookup();this.saveDomain(a)},this),{any:!0})},initDomainLookup:function(){var a=!1;return function(){a||(a=!0,e.on("DOMReady",e.bind(this.getDomains,this)))}}(),onDomainApi:function(){var k=e.destructing(function(){a.initLinks()});return function(l){var q=a.opt("blacklist_domains"),b=a.opt("commercial_domains")||{},c=e.destructing(function(){q=q||{}});e.each(l.results,function(a,e){b[e]=!0;a.unlink&&(c(),q[e]=!0)});a.opt("commercial_domains",b);
a.opt("blacklist_domains",q);k()}}(),saveDomain:function(a){a=e.canonicalizeHostname(a);r[a]=r[a]||1},unlinkBlacklisted:function(k){a.isBlacklisted(k)&&e.unlink(k)}};return{init:e.bind(q.init,q),initNodes:function(){q.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(l,e,a){var r=[],k=a.platform();l={crawl:function(a){if(k&&!("array"!==e.type(a)||0===a.length))a=e.all(a,function(a){return!e.contains(r,a)}),a=this.findPostsById(a),e.each(a,e.bind(function(a){a.content=this.redact(a.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete a.el},this)),a=e.all(a,function(a){return Boolean(a.content&&a.id)}),0<a.length&&this.processPosts(a)},findPostsById:function(a){return e.all(e.map(k.getPosts(),function(a){return{el:a,id:k.getPostId(a)}}),
function(k){return e.contains(a,k.id)})},processPosts:function(l){l=e.map(l,function(a){r.push(a.id);return{c:a.content,i:a.id}});a.api("content",{content:e.toJSON({ct:l,pt:k.id,u:window.document.location.href})},{jsonp:!1})},redact:function(a){return e.pii.redact(a)}};return{"public":{crawl:e.bind(l.crawl,l)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,e,a){return{init:function(){a.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.privacy_plugin=function(l,e,a){return{init:function(){l.domains&&a.opt("private_domains",l.domains)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,e,a){l=e.extend({key:null},l);var r={init:function(a){e.each(this.getDRSearchForms(a),function(a){if(!e.cache(a,"evented")){var k=r.getInput(a),l=function(){k.value||e.css(k,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};e.cache(a,"evented",!0);a.onsubmit=null;k.onfocus=null;k.onblur=null;e.on(k,"focus",function(){e.css(k,{"background-image":"none"})});e.on(k,"blur",l);l();e.on(a,"submit",function(e){r.onSubmit(e,a)})}})},
getDRSearchForms:function(a){var l=[];e.each(a,function(a){"element"===e.type(a)&&e.each(a.getElementsByTagName("form"),function(a){r.getInput(a)&&a.id.match(/^DR-ebay-search(CSS|2)?$/i)&&l.push(a)})});return l},getInput:function(a){return a.p||a.q2},onSubmit:function(k,q){k=k||window.event;var s="http://shop.ebay.com/i.html?"+e.toQuery({_nkw:r.getInput(q).value}),s=e.createA(s,"_blank");e.cache(s,"params",{key:l.key});a.click(s);return e.preventDefault(k)}};if(l.key)return{init:e.bind(r.init,r),
initNodes:function(a){r.init(a)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(l,e,a){l=e.extend({level:e.harmony.DEFAULT},l);return{init:function(){var e=parseFloat(l.level,10);isFinite(e)&&a.opt("harmony_level",e)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(l,e){l=e.extend({exclude_page_title:null,exclude_link_text:null},l);return{init:function(){var a={opt:!0};null!==l.exclude_page_title&&e.extend(a,{optExTitle:l.exclude_page_title});null!==l.exclude_link_text&&e.extend(a,{optExText:l.exclude_link_text});e.cache("opt_params",a)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(l,e,a,r){var k,q,s,v,A=null,b=!1,c=null;l=e.extend({cat:null,dynamic_sample_rate:1,heading_threshold:2,insertion_order:"api",key:null,link_headings:!1,link_phrases:!0,link_target:null,link_urls:!0,manual_mode:1===l.mode,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},l);"api"!==l.insertion_order&&"dom"!==l.insertion_order&&(l.insertion_order="api");if(l.key)return k=a.platform(),q={cache:function(){var a,b,c=function(){a={};b={}},
h=function(c,g){var h,k=b,l=a,m={};g=g||[e.platforms.DEFAULT_POST_ID];h=e.all(e.unique(e.map(g,function(a){return k[a]})),function(a){return null!==a});e.find(h,function(a){if(l[a]&&l[a].data&&l[a].order){if(c)return m[c]=l[a].data[c],!0;e.each(l[a].order,function(b){var c=l[a].data[b];m[b]||(m[b]=c)})}});return c?m[c]:m},k=function(c,g,h,k){var l=a,m=b;h=h||"-";k=k||[e.platforms.DEFAULT_POST_ID];l[h]=l[h]||{data:{},order:[]};l[h].data[c]||(l[h].data[c]=g,l[h].order.push(c));e.each(k,function(a){m[a]=
h});return!0},q=function(a,b,c,d){var f=e.all(e.toArray(arguments),function(a){return Boolean(a)});"array"===e.type(f[f.length-1])&&(d=f.pop());a=f[0];b=f[1];if(1>=f.length)return h(a,d);if(2<=f.length)return k(a,b,c,d)};l.manual_mode&&e.extend(q,{reset:c});c();return q}(),enabled:function(){return l.link_phrases||l.link_urls},focusLink:function(a){a.id||(a.id=e.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var b,c,e=a.opt("partner"),h={};for(b in e)break;
if(b)for(c in e[b])h[b+"_"+c]=e[b][c];return h},getPhrases:function(b,c){r.eventTimer.start("ins");a.api("insert",e.extend(q.getPartnerParams(),{cat:l.cat,i:c?c.join("|"):null,mode:l.mode,pt:k.id,ps:l.product_source,u:window.document.location.href,v:"2.0"}),{fn:e.apiCallback(q.onInsertApi,q)},b,c)},hasCalled:function(){var a={},b=Math.random()<l.dynamic_sample_rate,c=function(a){return b&&e.isArray(a)?e.map(a,function(a){return c(a)}):b&&a===e.platforms.DEFAULT_POST_ID?window.document.location.href:
a},h=function(b){b=c(b);return e.isArray(b)&&b.length?Boolean(e.all(b,function(b){return a[b]}).length===b.length):Boolean(a[e.platforms.DEFAULT_POST_ID])},k=function(b){b=c(b);e.isArray(b)&&b.length?e.each(b,function(b){a[b]=!0}):a[e.platforms.DEFAULT_POST_ID]=!0};return function(a,b){return b?k(a):h(a)}}(),init:function(){r.eventTimer.start("insert-init-run");l.scope=l.scope||k.scope;l.link_urls&&(v=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com\\b/?)(?!\\.[a-z0-9-]+))",
"i"))},initLink:function(){return function(b,c,g){var h=l.link_target;if(h="U"===c.type?a.opt("link_target"):h||g)b.target=h;b.href||(b.href=c.url);b.rel="nofollow";e.cache(b,"params",{exp:A,iid:c.iid,key:l.key,mid:c.mid,type:c.type||null});if(!0===c.auc){c=e.fromQuery(b.search);if(g=c.u||c.out)delete c.format,delete c.out,delete c.u,e.extend(c,a.clickParams(b),{out:g}),b.search="?"+e.toQuery(c);e.cache(b,"auctioned",!0)}e.cache(b,"href",b.href);a.link(b)}}(),insertLinks:function(){var c=e.generateNodeFilter({classes:["nolinks",
"atma-nolink","atma-nolinks"],tags:["map"],custom:function(a){return e.matches(a,"a")&&Boolean(a.href)}}),f=function(a,b,c,d){var f={phrase_to_nodes:{},regexp_cache:{},stats:{}};e.each(b,function(b){h(a,b,c,d,f)},{timeout:!0});"api"===l.insertion_order&&g(c,f);return f.stats},g=function(a,b){var c=s(a);c.push("&!UNLINKED!&");e.each(c,function(c){(c=b.phrase_to_nodes[c])&&e.each(c,function(c){p(c,c.data,a,b)})})},h=function(b,e,f,g,l){if(a.allowed(e)&&c(e,{ancestors:!Boolean(g),self:!0}))if(3===e.nodeType)k(b,
e,f,l);else if(1===e.nodeType)for(e=e.firstChild;e;)g=e.nextSibling,h(b,e,f,!0,l),e=g},k=function(){var a=function(a,b){var c=[];e.each(a,function(a){var d;b[a]?d=b[a]:(d=e.escapeRegExp(a).split(" ").join("\\s+"),d=RegExp("(?:^|[\\s\"'\\(])("+d+")(?=\\s|\\W*$|\\W{2})","i"),b[a]=d);c.push(d)});l.link_urls&&v&&c.push(v);return c},b=function(a,b){var c=s(b);a=q.normalizePhrase(a);return e.all(c,function(b){return-1!==a.indexOf(b)})};return function(c,d,f,g){var h,k,m=!1,p=g.phrase_to_nodes,u=g.regexp_cache;
d.parentNode&&(d.data&&(m=c.test(d.data.replace(/\s+/," "))),m&&"dom"===l.insertion_order?n(c,d,f,g):m&&"api"===l.insertion_order&&(h=b(d.data,f),c=a(h,u),k=[d],e.each(c,function(a){var b=[];e.each(k,function(c){for(var d,f,g,k,l;c&&(c.data&&""!==c.data&&(Boolean(!e.traits.fastRegexp&&(g=c.data.match(/^\s+/)))||Boolean(g=c.data.match(a))))&&g.input!==d;)d=g.input,f=g.slice(1).join(""),k=q.normalizePhrase(f),f=A(c,g),f.previous&&f.previous.data&&b.push(f.previous),c=f.next,l=e.contains(h,k)?k:"&!UNLINKED!&",
k=p,f=f.match,k[l]||(k[l]=[]),k[l].push(f);c&&!g&&b.push(c)},{timeout:!0});k=b})))}}(),s=function(a){a=q.cache(a);return e.map(a,function(a,b){return b})},n=function(a,b,c,d){for(var f,g,h;b&&(b.data&&""!==b.data&&(Boolean(!e.traits.fastRegexp&&(h=b.data.match(/^\s+/)))||Boolean(h=b.data.match(a))))&&h.input!==f;)f=h.input,g=h.slice(1).join(""),b=A(b,h),p(b.match,g,c,d),b=b.next},p=function(){var b=function(a,b){var c,d;if(a&&"U"===a.type)return!0;c=!a||!l.per_phrase||!b[a.phrase]||b[a.phrase].count<
l.per_phrase;d=!l.per_page&&0!==l.per_page||e.reduce(0,b,function(a,b){return a+("U"!==b.type?b.count:0)})<l.per_page;return c&&d},c=function(b,c,d){var f,g=Boolean(a.opt("dynamic_scope")),h=function(){var a,c;if(!d.phrase)return!0;if(l.proximity||l.same_proximity)c=e.geometry(f),e.find(q.cache(b),function(b){var f,g;if(b.links){if((f=q.normalizePhrase(b.phrase)===q.normalizePhrase(d.phrase))&&!l.same_proximity||!f&&!l.proximity)return!1;g=f?Math.max(l.same_proximity,l.proximity):l.proximity;b.links=
e.all(b.links,function(b){var d=e.isInDom(b.el);!a&&d&&(a=e.find(b.segments,function(a){a=a.geometry;a=e.extend({},a);a.x1-=g;a.y1-=g;a.x2+=g;a.y2+=g;if(a.x1<c.x2&&a.x2>c.x1&&a.y1<c.y2&&a.y2>c.y1)return!0}));return d});return a}});return!a};if(!c.parentNode)return!1;f=e.createEl("span");c.parentNode.insertBefore(f,c);f.appendChild(c);return function(a){f.parentNode.insertBefore(c,f);f.parentNode.removeChild(f);return a}((!g||e.isVisible(f))&&h())};return function(d,f,g,h){var k;h=h.stats;var m=q.normalizePhrase(f),
m=f?q.cache(m,g):null;f&&!m&&(m={url:f.match(/^https?:\/\//i)?f:"http://"+f,type:"U"});var n;if(n=m)if(n=m.url.match(/https?:\/\//i))if(n=f)if(n=b(m,h)){if(g=c(g,d,m)){var p;l.link_headings||!(p=e.css(d.parentElement,"font-size"))?g=!0:(p=parseFloat(p),g=0>=p||p/e.page.font_size<l.heading_threshold)}n=g}if(n&&(g=m,p=e.createEl("a"),p.innerHTML=f.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>"),p.className="vglnk",e.cache(p,"type","inserted"),e.cache(p,"phrase",f),l.ui&&"U"!==g.type&&(p.title=
"Link added by VigLink"),q.initLink(p,g),!e.cache(p,"unlinked")&&!a.isBlacklisted(p))){f=d.parentNode;f.insertBefore(p,d);f.removeChild(d);d=m;f={el:p,segments:[]};var r=p.getElementsByTagName("span"),s={els:[]};p=0;for(g=r.length;p<g;p++)n=r[p],void 0===k||n.offsetTop===k.offsetTop?s.els.push(n):(f.segments.push(s),s={els:[n]}),k=n;s.geometry=e.geometry.apply(e,s.els);f.segments.push(s);d.links=d.links||[];d.links.push(f);k=m.phrase||m.url;h[k]=h[k]||{count:0,iid:m.iid,imp:m.imp,phrase:m.phrase,
url:m.url,type:m.type};h[k].count++}}}(),A=function(a,b){var c,d;d=b.slice(1).join("");c=b.index+b[0].length-d.length;0<c?c=a.splitText(c):(c=a,a=null);d=c.length<=d.length?null:c.splitText(d.length);return{previous:a,match:c,next:d}};return function(a,g){var h,k={};r.eventTimer.start("insert-run");if(h=q.regexp(g))(a=e.all(a,c))&&a.length&&(k=f(h,a,g,!1)),l.link_phrases&&q.sendInsertedTerms(k);r.eventTimer.stop("insert-run",!0);b||(b=!0,r.eventTimer.stop("insert-init-run",!0))}}(),insertManually:function(){var a=
!1,b=e.clone(l),c=function(a){return e.map(a,function(a,b){return{iid:"00000000",phrase:b,type:"0",url:a}})};return function(h,k,r){var n,p=!1;s.init();l.manual_mode&&!a&&(a=!0,n=k=k||{},l.same_proximity=n.same_proximity||l.same_proximity,l.proximity=n.proximity||l.proximity,l.per_page=n.per_page||l.per_page,l.per_phrase=n.per_phrase||l.per_phrase,n=k.target_node||document.body,h=c(h),q.loadPhrases(h,null,[n]),l=b,q.cache.reset(),p=!0,a=!1);"function"===e.type(r)&&r(p,n)}}(),loadPhrases:function(a,
b,c,h){e.each(a,function(a){a.phrase&&(a.url&&a.iid)&&(a.phrase=q.normalizePhrase(a.phrase),q.cache(a.phrase,{auc:a.auc,count:0,iid:a.iid,imp:b,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},b,h))});q.hasCalled(h,!0);this.insertLinks(c,h)},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},onInsertApi:function(a,b,g){r.eventTimer.stop("ins");"object"===e.type(a)&&(A=a.exp,c=a.imp_id,a.results&&this.loadPhrases(a.results,c,b,g))},regexp:function(a){var b;
a=q.cache(a);a=e.map(a,function(a,b){return e.escapeRegExp(b).split(" ").join("\\s+")});0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(v?"(?:"+b+"|"+v.source+")":b,"i"));return b||v},sendInsertedTerms:function(b){b=e.map(b,function(a,b){return{count:a.count,phrase:b,iid:a.iid,impId:a.imp,url:a.url,type:a.type}});b.length&&a.apiNow("inserted",{cat:l.cat,exp:A,terms:e.toJSON(b),u:window.document.location.href,v:"2.0"})}},s={init:e.destructing(e.bind(q.init,q)),initNodes:function(b){var c=
[],g=[],h=[];q.enabled()&&(l.scope?(e.each(b,function(a){var b=e.withScope([a],l.scope,{ancestors:!0,consolidate:!0,descendants:!1,self:!0});b.length?(h.push(a),g=g.concat(b)):(a=e.withScope([a],l.scope,{ancestors:!1,consolidate:!0,descendants:!0,self:!1}),a.length&&(h=h.concat(a),g=g.concat(a)))},{timeout:!0}),h=e.unique(h),g=e.unique(g)):g=h=b,Boolean(a.opt("dynamic_scope"))&&(h=e.all(h,function(a){return!e.matches(a,":has(a.vglnk)")},{timeout:!0})),h.length&&(g.length&&(c=k.getPostIds(g)),l.link_phrases&&
!q.hasCalled(c)?q.getPhrases(h,c):q.insertLinks(h,c)))}},l.manual_mode&&e.extend(s,{"public":{run:q.insertManually}}),s};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(l,e,a){var r;l=e.extend({log_links:!0,log_status:!1,pai_type:null,sync_type:null,scope:"body"},l);r={initLinkLogger:function(){a.registerProcessor(function(k){a.sendLinks("optimize",{desc:e.page.description,links:[k.href],mode:["P"],title:e.page.title,u:e.context(k).document.location.href,ver:a.opt("links_version")},{jsonp:!1})},{scope:l.scope})},logStatus:function(k){e.createEl("img").src=e.updateUrl(a.opt("sync_url"),{pathname:"/api/sync/status.gif",search:"?"+
e.toQuery({st:k})})},run:function(){l.log_links&&r.initLinkLogger();l.pai_type?r.sync("partner",l.pai_type):l.sync_type&&r.sync(l.sync_type)},sync:function(){return function(k,q){var s,v,A;s="pixel";if("partner"===k)if(e.isArray(q)&&q.length)v={partner_id:q.shift()},A="/api/sync.gif";else return;else if(e.contains(["pixel","script"],k))q=null,v={key:a.opt("key")},"pixel"===k?A="/api/sync.gif":(s="script",A="/api/sync.js");else return;v=e.updateUrl(a.opt("sync_url"),{pathname:A,search:"?"+e.toQuery(v)});
l.log_status&&r.logStatus("bg");"script"===s?(r.sync("pixel",q),e.jsonp(v)):(s=e.createEl("img"),e.on(s,"load",function(){var a=q;l.log_status&&r.logStatus("su");a&&r.sync(k,a)}),e.on(s,"error",function(){var a=q;l.log_status&&r.logStatus("fa");a&&r.sync(k,a)}),s.src=v)}}()};return{init:function(){r.run()}}};
